# Generated by Django 3.0.7 on 2020-07-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_auto_20200707_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='unid',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
