# Generated by Django 3.0.8 on 2020-07-06 09:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registry', '0003_auto_20200706_0925'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseSheet',
            new_name='SheetRegister',
        ),
    ]
