# Generated by Django 3.0.8 on 2020-07-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_auto_20200706_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
