# Generated by Django 3.0.8 on 2020-07-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0005_aircraft_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
