# Generated by Django 3.0.8 on 2020-07-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0006_auto_20200706_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typecertificate',
            name='type_certificate_holder',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='typecertificate',
            name='type_certificate_holder_country',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='typecertificate',
            name='type_certificate_id',
            field=models.CharField(blank=True, max_length=280, null=True),
        ),
        migrations.AlterField(
            model_name='typecertificate',
            name='type_certificate_issuing_country',
            field=models.CharField(blank=True, max_length=280, null=True),
        ),
    ]
