# Generated by Django 3.0.8 on 2020-07-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0007_auto_20200706_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='unid',
            field=models.IntegerField(default=None, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
