# Generated by Django 3.0.7 on 2020-07-31 09:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0012_auto_20200730_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='category',
            field=models.CharField(choices=[('Other', 'Other'), ('FIXED WING', 'FIXED WING'), ('ROTORCRAFT', 'ROTORCRAFT'), ('LIGHTER-THAN-AIR', 'LIGHTER-THAN-AIR'), ('HYBRID LIFT', 'HYBRID LIFT'), ('MULTI-COPTER', 'MULTI-COPTER')], default='Other', max_length=50),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='sub_category',
            field=models.IntegerField(choices=[('Other', 'Other'), ('AIRPLANE', 'AIRPLANE'), ('NONPOWERED GLIDER', 'NONPOWERED GLIDER'), ('POWERED GLIDER', 'POWERED GLIDER'), ('HELICOPTER', 'HELICOPTER'), ('GYROPLANE', 'GYROPLANE'), ('BALLOON', 'BALLOON'), ('AIRSHIP', 'AIRSHIP'), ('UAV', 'UAV')], default=7),
        ),
        migrations.AlterField(
            model_name='authorization',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 31, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='operator',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 31, 0, 0, tzinfo=utc)),
        ),
    ]
