# Generated by Django 3.0.7 on 2020-10-08 06:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0023_auto_20201007_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='sub_category',
            field=models.IntegerField(blank=True, choices=[('Other', 'Other'), ('AIRPLANE', 'AIRPLANE'), ('NONPOWERED GLIDER', 'NONPOWERED GLIDER'), ('POWERED GLIDER', 'POWERED GLIDER'), ('HELICOPTER', 'HELICOPTER'), ('GYROPLANE', 'GYROPLANE'), ('BALLOON', 'BALLOON'), ('AIRSHIP', 'AIRSHIP'), ('UAV', 'UAV')], default=7, null=True),
        ),
        migrations.AlterField(
            model_name='authorization',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 8, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='operator',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 8, 0, 0, tzinfo=utc)),
        ),
    ]
