# Generated by Django 3.0.7 on 2020-10-08 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0024_auto_20201008_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='esn',
            field=models.CharField(blank=True, default='000000000000000000000000000000000000000000000000', max_length=48, null=True),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='icao_aircraft_type_designator',
            field=models.CharField(blank=True, default='0000', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='maci_number',
            field=models.CharField(blank=True, max_length=280, null=True),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='max_certified_takeoff_weight',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=10, null=True),
        ),
    ]
