# Generated by Django 3.0.7 on 2020-10-08 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0025_auto_20201008_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='model',
            field=models.CharField(blank=True, max_length=280, null=True),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Inactive'), (1, 'Active')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='sub_category',
            field=models.IntegerField(blank=True, choices=[('Other', 'Other'), ('AIRPLANE', 'AIRPLANE'), ('NONPOWERED GLIDER', 'NONPOWERED GLIDER'), ('POWERED GLIDER', 'POWERED GLIDER'), ('HELICOPTER', 'HELICOPTER'), ('GYROPLANE', 'GYROPLANE'), ('BALLOON', 'BALLOON'), ('AIRSHIP', 'AIRSHIP'), ('UAV', 'UAV')], null=True),
        ),
    ]
