# Generated by Django 3.0.7 on 2020-10-08 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0026_auto_20201008_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registry.Address'),
        ),
    ]
