# Generated by Django 3.0.7 on 2020-10-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0027_auto_20201008_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='authorized_activities',
            field=models.ManyToManyField(blank=True, null=True, related_name='authorized_activities', to='registry.Activity'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='operational_authorizations',
            field=models.ManyToManyField(blank=True, null=True, related_name='operational_authorizations', to='registry.Authorization'),
        ),
    ]
