# Generated by Django 3.0.7 on 2020-11-30 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0030_auto_20201014_1639'),
        ('registry', '0030_auto_20201013_1013'),
    ]

    operations = [
    ]
