# Generated by Django 3.1.3 on 2020-12-09 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0031_merge_20201130_1129'),
        ('registry', '0034_auto_20201202_0829'),
    ]

    operations = [
    ]
