# Generated by Django 3.1.3 on 2020-12-14 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0038_auto_20201214_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
