# Generated by Django 3.1.3 on 2021-12-08 08:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0039_aircraft_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='authorization',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 8, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='operator',
            name='expiration',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 8, 0, 0, tzinfo=utc), null=True),
        ),
    ]
