# Generated by Django 3.1.3 on 2020-12-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0039_aircraft_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
