# Generated by Django 3.1.3 on 2021-12-10 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0047_auto_20210108_1114'),
        ('registry', '0040_auto_20211208_1414'),
    ]

    operations = [
    ]
