# Generated by Django 3.1.3 on 2022-01-20 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0048_auto_20211101_2152'),
        ('registry', '0051_auto_20211225_1835'),
    ]

    operations = [
    ]
