version: "3"

services:
  web:
    build: .
    restart: always
    container_name: drone-reg-dev
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app/
    command: sh entrypoint-dev.sh
    env_file:
      - env.txt
    networks:
      - d-network
networks:
  d-network:
    external: false