# Generated by Django 3.1.3 on 2022-05-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID_quantification_planning', models.CharField(max_length=100)),
                ('UID_planning', models.CharField(max_length=100)),
                ('product_type', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=100)),
                ('UID_product', models.CharField(max_length=100)),
                ('delivery_product', models.CharField(max_length=100)),
                ('expected_quantity', models.CharField(max_length=100)),
                ('quantity_sent', models.CharField(max_length=100)),
                ('quantity_received', models.CharField(max_length=100)),
                ('quantity_intact', models.CharField(max_length=100)),
                ('quantity_damage', models.CharField(max_length=100)),
                ('quantity_lost', models.CharField(max_length=100)),
            ],
        ),
    ]
