# Generated by Django 3.1.3 on 2022-04-05 15:59

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_id', models.CharField(max_length=7)),
                ('clinic_name', models.CharField(max_length=20)),
                ('medication', models.CharField(max_length=20)),
                ('units', models.CharField(max_length=5)),
                ('delivery_date', models.DateField(default=django.utils.timezone.now)),
                ('take_of_time', models.TimeField(default=datetime.time(0, 0))),
                ('delivery_time', models.TimeField(default=datetime.time(0, 0))),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processed', 'Processed'), ('Dispatched', 'Dispatched'), ('Delayed', 'Delayed'), ('Completed', 'Completed')], default='dispatched', max_length=30)),
                ('destination', models.CharField(max_length=20)),
                ('delay_reasons', models.CharField(default='Air Traffic', max_length=20)),
            ],
        ),
    ]
