# Generated by Django 3.1.3 on 2022-03-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processed', 'Processed'), ('Dispatched', 'Dispatched'), ('Delayed', 'Delayed'), ('Completed', 'Completed')], default='dispatched', max_length=30),
        ),
    ]
