# Generated by Django 3.1.3 on 2022-05-15 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedules',
            old_name='UID_product',
            new_name='UID_produit',
        ),
        migrations.RenameField(
            model_name='schedules',
            old_name='delivery_product',
            new_name='explication',
        ),
        migrations.RenameField(
            model_name='schedules',
            old_name='expected_quantity',
            new_name='produit',
        ),
        migrations.RenameField(
            model_name='schedules',
            old_name='product',
            new_name='quantite_abime',
        ),
        migrations.RenameField(
            model_name='schedules',
            old_name='product_type',
            new_name='quantite_envoyee',
        ),
        migrations.RenameField(
            model_name='schedules',
            old_name='quantity_damage',
            new_name='quantite_intact',
        ),
        migrations.RenameField(
            model_name='schedules',
            old_name='quantity_intact',
            new_name='quantite_perdu',
        ),
        migrations.RenameField(
            model_name='schedules',
            old_name='quantity_lost',
            new_name='quantite_prevu',
        ),
        migrations.RenameField(
            model_name='schedules',
            old_name='quantity_received',
            new_name='quantite_recu',
        ),
        migrations.RenameField(
            model_name='schedules',
            old_name='quantity_sent',
            new_name='type_produit',
        ),
    ]
