# Generated by Django 3.1.3 on 2022-04-09 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_auto_20220319_0133'),
        ('shipments', '0002_delayed'),
    ]

    operations = [
    ]
