# Generated by Django 3.1.3 on 2022-05-15 19:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_auto_20220516_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedules',
            name='livraison_produit',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
