# Generated by Django 3.1.3 on 2022-04-06 20:29

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0003_merge_20220407_0209'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Delayed',
        ),
        migrations.AddField(
            model_name='schedule',
            name='delay_reasons',
            field=models.CharField(default='Air Traffic', max_length=20),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='delivery_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='delivery_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='take_of_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
