# # Generated by Django 3.1.3 on 2021-12-10 11:26

# from django.db import migrations, models
# # import phonenumber_field.modelfields


# class Migration(migrations.Migration):

#     initial = True

#     dependencies = [
#     ]

#     operations = [
#         migrations.CreateModel(
#             name='ClinicProfile',
#             fields=[
#                 ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
#                 ('clinic_name', models.CharField(max_length=50)),
#                 ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
#                 ('location', models.CharField(max_length=60)),
#                 ('registration_number', models.CharField(default=None, max_length=60)),
#             ],
#         ),
#     ]
