# Generated by Django 3.1.3 on 2022-05-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlightRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID_planning', models.CharField(max_length=300)),
                ('pays', models.CharField(max_length=300)),
                ('region', models.CharField(max_length=300)),
                ('district', models.CharField(max_length=300)),
                ('commune', models.CharField(max_length=300)),
                ('Centre', models.CharField(max_length=300)),
                ('type_centre', models.CharField(max_length=300)),
                ('UID_centre', models.CharField(max_length=300)),
                ('code_vol', models.CharField(max_length=300)),
                ('date_planning', models.CharField(max_length=300)),
                ('heure_planning', models.CharField(max_length=300)),
                ('situation_vol', models.CharField(max_length=300)),
                ('situation_livraison', models.CharField(max_length=300)),
                ('motif_report', models.CharField(max_length=300)),
                ('motif_annulation', models.CharField(max_length=300)),
                ('project', models.CharField(max_length=300)),
            ],
        ),
    ]
