# Generated by Django 3.1.3 on 2022-05-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_flightrequest_delayed_reasons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Scheduled', 'Scheduled'), ('Delayed', 'Delayed')], default='Pending', max_length=30),
        ),
    ]
