# Generated by Django 3.1.3 on 2022-11-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_auto_20221106_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightrequest',
            name='delayed_reasons',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='flightrequest',
            name='medication',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
