# Generated by Django 3.1.3 on 2021-12-08 08:41

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20201202_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicProfile',
           
        ),
    ]
