# Generated by Django 3.1.3 on 2021-12-20 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_clinicprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClinicProfile',
        ),
    ]
