# Generated by Django 3.0.6 on 2020-06-05 09:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlightRegistry',
            fields=[
                ('uav_uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('flight_date', models.DateTimeField()),
                ('flight_purpose', models.CharField(max_length=200)),
                ('flight_plan', models.FileField(upload_to='uploads/FlightPlan')),
                ('flight_insurance', models.FileField(upload_to='uploads/Insurance')),
                ('pilot_name', models.CharField(max_length=50)),
                ('pilot_phone_number', models.CharField(max_length=15)),
                ('pilot_cv', models.FileField(upload_to='uploads/PilotCV')),
            ],
        ),
        migrations.CreateModel(
            name='WhatsappComplain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(default='')),
                ('location', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('complainer_name', models.CharField(max_length=50)),
                ('complainer_number', models.CharField(max_length=15)),
                ('photo', models.FileField(upload_to='uploads/WhComplains')),
                ('note', models.TextField()),
                ('reply', models.TextField(default='')),
                ('is_escalated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
