# Generated by Django 3.1.3 on 2020-12-14 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registry', '0040_auto_20201214_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalAuthorities',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('authority_type', models.CharField(blank=True, choices=[('Police', 'Police'), ('Others', 'Others')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NoFlyZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spatialdata_zip_file', models.FileField(blank=True, null=True, upload_to='shp_files')),
            ],
        ),
        migrations.CreateModel(
            name='Pilots',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('cv_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('uav_uid', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField(default='')),
                ('location', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('complainer_name', models.CharField(blank=True, max_length=50, null=True)),
                ('complainer_number', models.CharField(blank=True, max_length=30, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Resolved', 'Resolved')], default='Pending', max_length=15)),
                ('reply', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, default='', null=True)),
                ('is_escalated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlightPermission',
            fields=[
                ('uav_uid', models.AutoField(primary_key=True, serialize=False)),
                ('existing_permission_id', models.IntegerField(blank=True, null=True)),
                ('flight_start_date', models.DateField(blank=True, null=True)),
                ('flight_end_date', models.DateField(blank=True, null=True)),
                ('flight_time', models.CharField(blank=True, max_length=300, null=True)),
                ('flight_purpose', models.CharField(blank=True, max_length=200, null=True)),
                ('flight_plan_url', models.URLField(blank=True, null=True)),
                ('flight_insurance_url', models.URLField(blank=True, null=True)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('altitude', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=15)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('location', models.URLField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_special_permission', models.BooleanField(default=False)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_to', to=settings.AUTH_USER_MODEL)),
                ('pilot_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flightres.pilots')),
                ('uav_uuid', models.ForeignKey(blank=True, db_column='uav_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uav_uuid', to='registry.aircraft', to_field='unid')),
            ],
        ),
    ]
