# Generated by Django 3.0.7 on 2020-07-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightpermission',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='flightpermission',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=6, null=True),
        ),
    ]
