# Generated by Django 3.1.3 on 2022-04-05 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registry', '0001_initial'),
        ('flightres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightpermission',
            name='uav_uuid',
            field=models.ForeignKey(blank=True, db_column='uav_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uav_uuid', to='registry.aircraft', to_field='unid'),
        ),
    ]
