# Generated by Django 3.0.6 on 2020-06-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightres', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsappcomplain',
            name='id',
        ),
        migrations.AddField(
            model_name='whatsappcomplain',
            name='uav_uid',
            field=models.CharField(default=32423, max_length=20, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flightregistry',
            name='uav_uid',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
