# Generated by Django 3.1.3 on 2021-01-07 04:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flightres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Approve', 'Approve'), ('Deny', 'Deny')], max_length=15, null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('permission_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flightres.flightpermission')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
