# Generated by Django 3.0.7 on 2020-07-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightres', '0002_auto_20200706_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightpermission',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='flightpermission',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True),
        ),
    ]
