# Generated by Django 3.0.7 on 2020-07-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightres', '0002_auto_20200707_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='uploads/WhComplains'),
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Resolved', 'Resolved')], default='Pending', max_length=15),
        ),
    ]
