# Generated by Django 3.1.3 on 2021-01-07 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightres', '0002_permissionlogs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permissionlogs',
            old_name='date_time',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='permissionlogs',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
