# Generated by Django 3.1.3 on 2021-01-07 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightres', '0003_auto_20210107_1042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissionlogs',
            options={'verbose_name_plural': 'Permission Logs'},
        ),
        migrations.AlterField(
            model_name='permissionlogs',
            name='status',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=15, null=True),
        ),
    ]
