# Generated by Django 3.0.7 on 2020-07-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightres', '0003_auto_20200706_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightpermission',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='flightpermission',
            name='status',
            field=models.TextField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending'),
        ),
    ]
