# Generated by Django 3.0.7 on 2020-07-08 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightres', '0003_auto_20200707_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='photo',
        ),
    ]
