# Generated by Django 3.0.7 on 2020-07-17 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightres', '0004_remove_report_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightpermission',
            name='uav_uid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
