# Generated by Django 3.0.7 on 2020-06-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightres', '0005_auto_20200617_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappcomplain',
            name='category',
            field=models.TextField(default=''),
        ),
    ]
