# Generated by Django 3.0.7 on 2020-06-17 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightres', '0006_whatsappcomplain_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WhatsappComplain',
            new_name='Report',
        ),
    ]
