# Generated by Django 3.0.7 on 2020-06-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightres', '0007_auto_20200617_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='complainer_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
