# Generated by Django 3.0.7 on 2020-07-22 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightres', '0007_auto_20200722_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilots',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
