# Generated by Django 3.0.7 on 2020-07-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightres', '0008_auto_20200722_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightpermission',
            name='existing_permission_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
