# Generated by Django 3.0.7 on 2020-07-23 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightres', '0009_flightpermission_existing_permission_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reply',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
