# Generated by Django 3.0.7 on 2020-06-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightres', '0009_auto_20200617_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightregistry',
            name='flight_insurance',
        ),
        migrations.RemoveField(
            model_name='flightregistry',
            name='flight_plan',
        ),
        migrations.RemoveField(
            model_name='flightregistry',
            name='pilot_cv',
        ),
        migrations.AddField(
            model_name='flightregistry',
            name='flight_insurance_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flightregistry',
            name='flight_plan_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flightregistry',
            name='pilot_cv_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
