# Generated by Django 3.0.7 on 2020-06-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightres', '0010_auto_20200618_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightregistry',
            name='uav_uuid',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='flightregistry',
            name='flight_purpose',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='flightregistry',
            name='pilot_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='flightregistry',
            name='pilot_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='flightregistry',
            name='uav_uid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
