# Generated by Django 3.0.7 on 2020-06-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightres', '0011_auto_20200618_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightregistry',
            name='flight_date',
        ),
        migrations.AddField(
            model_name='flightregistry',
            name='flight_end_date',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='flightregistry',
            name='flight_start_date',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='flightregistry',
            name='flight_time',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
