# Generated by Django 3.0.7 on 2020-07-27 07:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flightres', '0011_auto_20200724_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightpermission',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
