# Generated by Django 3.0.7 on 2020-06-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightres', '0012_auto_20200618_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightregistry',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
