# Generated by Django 3.0.7 on 2020-07-30 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightres', '0012_flightpermission_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pilots',
            name='address',
        ),
        migrations.AddField(
            model_name='pilots',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pilots',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
