# Generated by Django 3.0.7 on 2020-06-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightres', '0013_flightregistry_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightregistry',
            name='pilot_phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
