# Generated by Django 3.0.7 on 2020-07-30 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightres', '0013_auto_20200730_0255'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalAuthorities',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('authority_type', models.CharField(blank=True, choices=[('Police', 'Police'), ('Others', 'Others')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
