# Generated by Django 3.0.7 on 2020-06-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightres', '0014_auto_20200618_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightregistry',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
