# Generated by Django 3.0.7 on 2020-06-18 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightres', '0015_flightregistry_is_approved'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FlightRegistry',
            new_name='FlightPermission',
        ),
    ]
