# Generated by Django 3.0.7 on 2020-08-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightres', '0015_auto_20200731_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightpermission',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flightpermission',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=15),
        ),
    ]
