# Generated by Django 3.0.7 on 2020-08-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightres', '0016_auto_20200814_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightpermission',
            name='is_special_permission',
            field=models.BooleanField(default=False),
        ),
    ]
