# Generated by Django 3.0.7 on 2020-10-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightres', '0018_auto_20200929_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightpermission',
            name='altitude',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
