# Generated by Django 3.1.3 on 2020-12-10 09:13

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightres', '0021_noflyzone_loc2'),
    ]

    operations = [
        migrations.AddField(
            model_name='noflyzone',
            name='loc3',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
