# Generated by Django 3.1.3 on 2020-12-10 09:23

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightres', '0022_noflyzone_loc3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noflyzone',
            old_name='loc3',
            new_name='location1',
        ),
        migrations.RemoveField(
            model_name='noflyzone',
            name='loc2',
        ),
        migrations.AlterField(
            model_name='noflyzone',
            name='location',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
    ]
