# Generated by Django 3.1.3 on 2020-12-10 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightres', '0023_auto_20201210_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noflyzone',
            name='location1',
        ),
        migrations.RemoveField(
            model_name='noflyzone',
            name='name',
        ),
    ]
