# Generated by Django 3.1.3 on 2020-12-11 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightres', '0024_auto_20201210_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='noflyzone',
            name='file_name',
            field=models.FileField(blank=True, null=True, upload_to='shp_files'),
        ),
    ]
