# Generated by Django 3.1.3 on 2020-12-11 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightres', '0025_noflyzone_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='noflyzone',
            name='json_file',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
