# Generated by Django 3.1.3 on 2020-12-11 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightres', '0026_noflyzone_json_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noflyzone',
            name='json_file',
        ),
    ]
