# Generated by Django 3.1.3 on 2020-12-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightres', '0027_remove_noflyzone_json_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='noflyzone',
            name='file_name1',
            field=models.FileField(blank=True, null=True, upload_to='shp_files'),
        ),
        migrations.AddField(
            model_name='noflyzone',
            name='file_name2',
            field=models.FileField(blank=True, null=True, upload_to='shp_files'),
        ),
        migrations.AddField(
            model_name='noflyzone',
            name='file_name3',
            field=models.FileField(blank=True, null=True, upload_to='shp_files'),
        ),
        migrations.AddField(
            model_name='noflyzone',
            name='file_name4',
            field=models.FileField(blank=True, null=True, upload_to='shp_files'),
        ),
        migrations.AddField(
            model_name='noflyzone',
            name='file_name5',
            field=models.FileField(blank=True, null=True, upload_to='shp_files'),
        ),
    ]
