# Generated by Django 3.1.3 on 2020-12-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightres', '0028_auto_20201211_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='noflyzone',
            name='geojson_file',
            field=models.FileField(blank=True, null=True, upload_to='geojson'),
        ),
    ]
