# Generated by Django 3.1.3 on 2020-12-11 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightres', '0029_noflyzone_geojson_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noflyzone',
            name='geojson_file',
        ),
    ]
