# Generated by Django 3.1.3 on 2020-12-11 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightres', '0030_remove_noflyzone_geojson_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noflyzone',
            old_name='file_name',
            new_name='shp_file',
        ),
        migrations.RemoveField(
            model_name='noflyzone',
            name='location',
        ),
    ]
