# Generated by Django 3.1.3 on 2020-12-11 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightres', '0032_auto_20201211_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noflyzone',
            name='shp_file',
        ),
        migrations.RemoveField(
            model_name='noflyzone',
            name='shx_file',
        ),
    ]
