# Generated by Django 3.1.3 on 2020-12-14 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightres', '0033_auto_20201211_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightpermission',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
